imports:
    - { resource: parameters.yml }
    - { resource: propel.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: de

framework:
    #esi: ~
    translator: { fallbacks: [ de, en ] }
    default_locale: de
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: [ 'twig' ]
        #assets_version: SomeVersionScheme
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # DEPRECATED! Session starts on demand
        #auto_start: false
        #storage_id: session.storage.native
        #storage_id: session.storage.filesystem
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
        #handler_id: session.handler.native_file
        name: FreakXoHBingoId
        #cookie_lifetime: ~
        #cookie_path: /
        cookie_domain: freakxohbingo.de
        #cookie_secure: ~
        #cookie_httponly: ~
        #gc_divisor: ~
        #gc_probability: ~
        #gc_maxlifetime: ~
        save_path: %kernel.cache_dir%/sessions
    fragments: ~
    http_method_override: true

sensio_framework_extra:
    view: { annotations: false }
    router: { annotations: true }
    request: { converters: true }
    cache: { annotations: true }

# Twig Configuration
twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        #resources: ['bootstrap_3_layout.html.twig']
        resources: ['bootstrap_3_horizontal_layout.html.twig']
    globals:
        fos_csrf_provider: "@form.csrf_provider"

# Assetic Configuration
assetic:
    debug: "%kernel.debug%"
    use_controller: false
    bundles: [ BingoBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
# if using pdo_sqlite as your database driver:
#   1. add the path in parameters.yml
#     e.g. database_path: "%kernel.root_dir%/data/data.db3"
#   2. Uncomment database_path in parameters.yml.dist
#   3. Uncomment next line:
#     path: "%database_path%"
#doctrine:
#    dbal:
#        driver: pdo_mysql
#        host: "%database_host%"
#        port: "%database_port%"
#        dbname: "%database_name%"
#        user: "%database_user%"
#        password: "%database_password%"
#        charset: UTF8
#    orm:
#        auto_generate_proxy_classes: "%kernel.debug%"
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host: "%mailer_host%"
    username: "%mailer_user%"
    password: "%mailer_password%"
    spool: { type: memory }

# FOS Rest Configuration
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    param_fetcher_listener: force
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    format_listener:
        rules:
            #fallback_format: json
            #prefer_extension: false
            #priorities: [ json, html ]
            - { path: ^/rest, priorities: [ json, html ], fallback_format: json, prefer_extension: false }
            - { path: ^/, priorities: [ html, json, xml ], fallback_format: ~, prefer_extension: true }
    routing_loader:
        default_format: ~
    view:
        view_response_listener: force
        mime_types:
            json: [ 'application/json; charset=UTF-8', 'application/json' ]

# FOS User Configuration
fos_user:
    db_driver: propel
    firewall_name: main
    user_class: FOS\UserBundle\Propel\User
    #user_class: BingoBundle\Model\User

# FOS oAuth Configuration
fos_oauth_server:
    db_driver: orm
    client_class: BingoBundle\Entity\Client
    access_token_class: BingoBundle\Entity\AccessToken
    refresh_token_class: BingoBundle\Entity\RefreshToken
    auth_code_class: BingoBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_manager.default
