propel:
    dbal:
        default_connection: default
        connections:
            default:
                driver: mysql
                user: %database_user%
                password: %database_password%
                dsn: mysql:host=%database_host%;dbname=%database_name%%database_charset%
    behaviors:
        behavior_name: My\Bundle\Behavior\BehaviorClassName
    build_properties:
        # MySQL specific
        propel.mysql.tableType: InnoDB
