propel:
    database:
        # All database sources
        connections:
            default:
                adapter: mysql
                dsn: mysql:host=%database_host%;dbname=%database_name%%database_charset%
                user: %database_user%
                password: %database_password%
        adapters:
            mysql:
                tableType: InnoDB
    #behaviors:
    #    typehintable: vendor.willdurand.propel-typehintable-behavior.src.TypehintableBehavior
